### ISSUE TITLE
真的很好用，后期会更新吗？密码能加一个生成规则吗？

### ISSUE THREAD

**Issue by badboycxcc** [seventh-letter/DictGenerate#1]
目前规则缺少一个就是，用户名@生日这种类型的。我觉得可以加上去，例如test、生日19981213。那么可以生成test@19991213、test@991213、Test@19991213等这种。

**Comment by telanflow** [comment]
好的👌🏻，这两天给你整上。

**Comment by telanflow** [comment]
v1.2.1 已经实现。 @badboycxcc
